config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :favorites, only: [:index, :destroy]

  root "home#index"
  resources :games, only: [:index]
  get '/hot' => 'games#hot'
  get '/not' => 'games#not'

end

app/models/home.rb
class Home < ActiveRecord::Base
  has_many :viewed_homes
  has_many :users, through: :viewed_homes
  validates_uniqueness_of :photo_url
  default_scope ->{ order("homes.created_at DESC") }

  def self.update_home(user, fav, home_id)
    home = Home.where(:id => home_id).first
    ViewedHome.create(home_id: home.id, user_id: user.id, favorite: fav)
    get_next_home(user)
  end

  def self.get_next_home(user)
    get_unseen_homes(user).first
  end

  def self.get_unseen_homes(user)
    Home.joins("LEFT OUTER JOIN (SELECT * FROM viewed_homes WHERE user_id = #{user.
      id}) AS viewed_homes ON homes.id = viewed_homes.home_id").
      where("viewed_homes.id IS NULL").to_a
  end

  def self.get_favorites(user)
    Home.joins("LEFT OUTER JOIN (SELECT * FROM viewed_homes WHERE user_id = #{user.
      id}) AS viewed_homes ON homes.id = viewed_homes.home_id").
      where("viewed_homes.favorite = true").to_a
  end

end

app/models/home_scraper.rb
require 'nokogiri'
require 'open-uri'
class HomeScraper
  attr_reader :url, :data

  def initialize(url)
    @url = url
  end

  def find_homes
    @data ||= Nokogiri::HTML(open(url))
    content_box = @data.
    xpath('//body/div[@id="searchResults"]/section/div[@id="leftColumn"]/div[@class="resultsBands last"]')
    content_box.each do |node|
      img = node.css(".propertyPhoto")[0]["src"]
      price = node.css(".price")[0].children[0].text
      address = node.css(".address").children[1].children[1].children[0].text
      desc = node.css(".propertyType").children.text
      Home.create(photo_url: img, list_price: price, address: address, description: desc)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :viewed_homes
  has_many :homes, through: :viewed_homes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter]

  validates_presence_of :email
  validates_presence_of :password, on: :create
  validates_uniqueness_of :email

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      if auth.info.email
        user.email = auth.info.email
      else
        user.email = "random#{rand(9999)}@random.com"
      end
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/models/viewed_home.rb
class ViewedHome < ActiveRecord::Base
  belongs_to :user
  belongs_to :home
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    games_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  respond_to :html, :js
  def index
    @favorites = Home.get_favorites(current_user)
  end

  def destroy
    home = ViewedHome.where("home_id = ?", params[:id]).first
    home.destroy!
    @favorites = Home.get_favorites(current_user)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :js
  def index
    @home = Home.get_next_home(current_user)
    @homes_list = get_homes_list
  end

  def hot
    @home = Home.update_home(current_user, true, params[:home_id])
    get_homes_list
  end

  def not
    @home = Home.update_home(current_user, false, params[:home_id])
    get_homes_list
  end

  private

  def scrape_homes
    @home_scrape = HomeScraper.new('http://www.homefinder.com/TN/Nashville/').find_homes
  end

  def get_homes_list
    @homes_list = Home.get_unseen_homes(current_user)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/_favorites_box.html.erb
<h1 class="favs">Favorites</h1>
<% if @favorites.empty? %>
  <div class="fav-box">
    <h1>You don't have any favorites!</h1>
    <%= link_to "Play", games_path, :class => "play mplay" %>
  </div>
<% else %>
  <% @favorites.each do |fav| %>
    <div class="fav-box">
      <img class="thumbnail" src="<%= fav.photo_url %>"/>
      <%= link_to "X", favorite_path(fav), :method => :delete, remote: true, :class => "nuke mnuke" %>
      <h3 class="list-price">
        <%= fav.list_price %>
      </h3>
      <p class="address">
        <%= fav.address %>
      </p>
      <p class="desc">
        <%= fav.description %>
      </p>
    </div>
  <% end %>
<% end %>

app/views/favorites/destroy.js.erb
$(".favorites-container").html("<%= escape_javascript(render partial: 'favorites_box', locals: { favorites: @favorites } ) %>");

app/views/favorites/index.html.erb
<div class="favorites-container" "data-no-turbolink">
  <%= render "favorites/favorites_box" %>
</div>

app/views/games/_game_play.html.erb
<div class="game-box">
  <% if @home.present? %>
    <img class="thumbnail animated flip" src="<%= @home.photo_url %>"/>
    <h3 class="list-price">
      <%= @home.list_price %>
    </h3>
    <p class="addy">
      <%= @home.address %>
    </p>
    <p class="desc">
      <%= @home.description %>
    </p>

    <div class="controls-container">
      <ul>
        <li>
          <%= link_to image_tag('hot.svg'),
           hot_path(home_id: @home.id),
            :class => "controls hot", remote: true %>
        </li>
        <li>
          <%= link_to image_tag('not.png'),
           not_path(home_id: @home.id),
            :class => "controls not", remote: true %>
        </li>
      </ul>
    <% else %>
      <h2>You've completed the game!</h2>
      <div class="fav-container">
        <%= link_to "Favorites", favorites_path, :class => "play" %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/_list_homes.html.erb
<div class="home-list">
  <h2>Local Hot List</h2>
  <% @homes_list.each do |home| %>
    <img class="list-pic" src="<%= home.photo_url %>"/>
  <% end %>
</div>

app/views/games/hot.js.erb
$(".game-play-container").html("<%= escape_javascript(render partial: 'game_play', locals: { home: @home } ) %>");
$(".list-homes-container").html("<%= escape_javascript(render partial: 'list_homes', locals: { homes_list: @homes_list } ) %>");

app/views/games/index.html.erb
<div class="game">
  <div class="game-play-container">
    <%= render "games/game_play" %>
  </div>
  <div class="list-homes-container">
    <%= render "games/list_homes" %>
  </div>
</div>

app/views/games/not.js.erb
$(".game-play-container").html("<%= escape_javascript(render partial: 'game_play', locals: { home: @home } ) %>");
$(".list-homes-container").html("<%= escape_javascript(render partial: 'list_homes', locals: { homes_list: @homes_list } ) %>");

app/views/home/index.html.haml
.logo-container
  %h1.main-logo Hot Or Not
  %h1.main-logo-second-line Nashville Home Edition

.button-container
  - if user_signed_in?
    %ul
      %li= link_to "Play", games_path, :class => "play"
      %li= link_to "Favorites", favorites_path, :class => "favorites"

.social-container
  - unless user_signed_in?
    %h3.social Sign in with:
    %img= link_to image_tag('facebook.png'),
    user_omniauth_authorize_path(:facebook),
    :class => "social", :id => "facebook"
    %img= link_to image_tag('twitter.png'),
    user_omniauth_authorize_path(:twitter),
    :class => "social", :id => "twitter"

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55154064-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/_header.html.haml
%header.navigation
  .navigation-wrapper
    %a.logo{:href => "/"}
      %img= image_tag('home-icon-square-red.png')
      %img= image_tag('home-icon-blue.png')
    %a#js-mobile-menu.navigation-menu-button{:href => ""} MENU
    .nav
      %ul#navigation-menu
        - if user_signed_in?
          - if current_user.name
            %li.nav-link.name #{current_user.name}
          - else
            %li.nav-link.name #{current_user.email}
          %li.nav-link
            %a= link_to "Play", games_path, :class => "logout"
          %li.nav-link
            %a= link_to "Favorites", favorites_path, :class => "logout"
        - else
          %a.sign-up{:href => new_user_registration_path} Sign Up
          %a.sign-up{:href => new_user_session_path} Sign In

    .navigation-tools
      - if user_signed_in?
        %a= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "logout"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Hot Or Not: Home Edition
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag    'animate', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "Hot or Not Nashville Real Estate Edition", :name => "description"}/
    %meta{:content => "Nashville,Real Estate,Listings,Web Developer,Game", :name => "keywords"}/
    %meta{:content => "Matt Spell", :name => "author"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
  %body
    = render "layouts/header"

    = notice
    = alert
    = yield